Add Unit Tests
hexploits/presidio-sdk pull request #3
Opened 2024-12-05 19:20 UTC by Tastebuder

<img width="1276" alt="Screenshot 2024-12-05 at 19 19 50" src="https://github.com/user-attachments/assets/f2283c8d-a21f-43a7-8a50-7455ac5391ec">

2024-12-05 20:38 UTC, CameronMukherjee requested changes

2024-12-05 20:38 UTC, CameronMukherjee commented on build.gradle
> -//    id 'java'
Is there any reason we disabled this?

2024-12-05 20:38 UTC, CameronMukherjee commented on src/main/java/com/hexploits/oss/sdk/presidio/anonymizer/strategy/MaskAnonymizerStrategy.java
> +        }
Can we add a new line?

2024-12-05 20:38 UTC, CameronMukherjee commented on src/test/java/com/hexploits/oss/sdk/presidio/analyzer/PresidioAnalyzerClientTest.java
> +                  "[{\"analysis_explanation\":null,\"recognition_metadata\":{\"recognizer_identifier\":\"recognizerIdentifier\",\"recognizer_name\":\"recognizerName\"},\"entity_type\":\"field2\",\"sc
Any chance we can move these to the test resource folder and read them in for the tests?

Might be more re-usable that way.

2024-12-05 20:58 UTC, Tastebuder commented on build.gradle
> -//    id 'java'
This was just commented out, so got rid since it was commented out

2024-12-05 21:25 UTC, CameronMukherjee commented on src/test/resources/AnalyzeResponse.json
Can we name this something that helps us re-use it across tests?

2024-12-06 09:22 UTC, CameronMukherjee commented on src/test/resources/AnalyzeResponse.json
Ideally something like: `analyse_reponse_(the type of response)`.

Would be great to also get this in it's own folder in `test`?

2024-12-07 12:43 UTC, CameronMukherjee commented on src/test/resources/AnalyzeResponse.json
Final request related to this, can we make it all lower case? Filename seems great though!

2024-12-07 20:19 UTC, Tastebuder commented on src/test/resources/AnalyzeResponse.json
Done 👍🏼

2024-12-08 12:04 UTC, CameronMukherjee approved these changes
LGTM

2024-12-08 12:04 UTC, merged